#!/usr/bin/env bun
// Dev-cycle latency benchmark — measures cold start + edit-bounce time
// for a synthetic 1000-component app served via `bun --watch` + serve().
//
// What we measure (and why):
//   - **Cold start**: spawn the watch process → first 200 on GET /
//     Reflects the cost of: TS resolution, ESM module graph load,
//     Bun.build of the client bundle, Tailwind compile (skipped here —
//     no tailwind in the synthetic app), Bun.serve startup. This is
//     the "I just edited a file from a cold cache" experience.
//   - **Edit-bounce**: touch one component file → next GET / reflects
//     the change. Uses `bun --watch`'s server-restart-on-change. Median
//     + tail latencies across 30 trials.
//
// Honest framing: place-ts has no module-level HMR (no
// `import.meta.hot` plumbing). What this measures is "edit → fresh
// render via process restart" — the practical dev cycle from a user's
// keystroke to seeing the change reflected in the browser.
//
// Output: JSON to stdout + Markdown table appended to docs/benchmarks/dev-cycle.md.
//
// Usage: bun scripts/bench-dev-cycle.ts [--components=N] [--trials=N]

import { spawn } from 'node:child_process'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

interface Args {
  components: number
  trials: number
}

function parseArgs(argv: string[]): Args {
  const args: Args = { components: 1000, trials: 30 }
  for (const a of argv.slice(2)) {
    const m = a.match(/^--(\w+)=(\d+)$/)
    if (!m) continue
    const [, key, val] = m
    if (key === 'components') args.components = Number(val)
    if (key === 'trials') args.trials = Number(val)
  }
  return args
}

async function generateApp(dir: string, n: number): Promise<void> {
  // One trivial .tsx per component, all imported by the root.
  // Each component is a function returning a div with its index — touching
  // any file triggers re-bundle, which is what we measure.
  const componentsDir = join(dir, 'components')
  await mkdir(componentsDir, { recursive: true })
  for (let i = 0; i < n; i++) {
    const src =
      `import { div } from '@place-ts/component'\n` +
      `export const C${i} = () => div({ class: 'c${i}' }, ['component ${i}'])\n`
    await writeFile(join(componentsDir, `c${i}.tsx`), src)
  }
  const imports = Array.from(
    { length: n },
    (_, i) => `import { C${i} } from './components/c${i}.ts'`,
  ).join('\n')
  const refs = Array.from({ length: n }, (_, i) => `C${i}()`).join(',\n  ')
  const clientSrc = `// Auto-generated by bench-dev-cycle.ts\n${imports}\n\nexport const all = [\n  ${refs}\n]\n`
  await writeFile(join(dir, 'client.tsx'), clientSrc)
  const serverSrc =
    `import { div, page, serve } from '@place-ts/component'\n` +
    `import { all } from './client.ts'\n\n` +
    `await serve({\n` +
    `  port: Number(process.env.PORT ?? 0),\n` +
    `  clientEntry: import.meta.dir + '/client.ts',\n` +
    `  routes: { '/': page({ view: () => div({}, all) }) },\n` +
    `  log: { banner: false, requests: false },\n` +
    `})\n`
  await writeFile(join(dir, 'server.tsx'), serverSrc)
}

async function waitForReady(port: number, timeoutMs = 30000): Promise<number> {
  const start = performance.now()
  while (performance.now() - start < timeoutMs) {
    try {
      const res = await fetch(`http://localhost:${port}/`, { signal: AbortSignal.timeout(1000) })
      if (res.ok) return performance.now() - start
    } catch {
      // not ready yet
    }
    await new Promise((r) => setTimeout(r, 50))
  }
  throw new Error(`server did not respond within ${timeoutMs}ms`)
}

function pickPort(): number {
  // Sloppy but sufficient: random ephemeral port. The benchmark's not
  // exposed to the network; collisions are unlikely and benign.
  return 30000 + Math.floor(Math.random() * 10000)
}

function median(xs: number[]): number {
  if (xs.length === 0) return 0
  const sorted = [...xs].sort((a, b) => a - b)
  const mid = Math.floor(sorted.length / 2)
  return sorted.length % 2 === 0
    ? ((sorted[mid - 1] ?? 0) + (sorted[mid] ?? 0)) / 2
    : (sorted[mid] ?? 0)
}

function pct(xs: number[], p: number): number {
  if (xs.length === 0) return 0
  const sorted = [...xs].sort((a, b) => a - b)
  const idx = Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length))
  return sorted[idx] ?? 0
}

interface Result {
  components: number
  trials: number
  coldStartMs: number
  editBounce: { p50: number; p95: number; p99: number; mean: number; samples: number[] }
}

async function run(args: Args): Promise<Result> {
  const tmp = join(tmpdir(), `place-bench-${Date.now()}`)
  await mkdir(tmp, { recursive: true })

  await generateApp(tmp, args.components)

  const port = pickPort()
  const env = { ...process.env, PORT: String(port) }

  const proc = spawn('bun', ['--watch', join(tmp, 'server.tsx')], {
    cwd: tmp,
    env,
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  const coldStart = await waitForReady(port)

  const editBounce: number[] = []
  for (let trial = 0; trial < args.trials; trial++) {
    const target = trial % args.components
    const file = join(tmp, 'components', `c${target}.tsx`)
    const newSrc =
      `import { div } from '@place-ts/component'\n` +
      `export const C${target} = () => div({ class: 'c${target}-r${trial}' }, ['component ${target} rev ${trial}'])\n`
    const editStart = performance.now()
    await writeFile(file, newSrc)
    // Wait for the change to be reflected in the served HTML.
    while (performance.now() - editStart < 30000) {
      try {
        const res = await fetch(`http://localhost:${port}/`, { signal: AbortSignal.timeout(1000) })
        const html = await res.text()
        if (html.includes(`c${target}-r${trial}`)) {
          editBounce.push(performance.now() - editStart)
          break
        }
      } catch {
        // not yet
      }
      await new Promise((r) => setTimeout(r, 25))
    }
  }

  proc.kill('SIGTERM')
  await rm(tmp, { recursive: true, force: true })

  return {
    components: args.components,
    trials: args.trials,
    coldStartMs: coldStart,
    editBounce: {
      p50: median(editBounce),
      p95: pct(editBounce, 95),
      p99: pct(editBounce, 99),
      mean: editBounce.reduce((a, b) => a + b, 0) / editBounce.length,
      samples: editBounce,
    },
  }
}

async function appendMarkdown(result: Result, outFile: string): Promise<void> {
  const date = new Date().toISOString().slice(0, 10)
  const eb = result.editBounce
  const row = `| ${date} | ${result.components} | ${result.trials} | ${result.coldStartMs.toFixed(0)} | ${eb.p50.toFixed(0)} | ${eb.p95.toFixed(0)} | ${eb.p99.toFixed(0)} | ${eb.mean.toFixed(0)} |\n`
  // Append to file; create with header if missing.
  const { existsSync, readFileSync } = await import('node:fs')
  if (!existsSync(outFile)) {
    const header =
      '# Dev-cycle latency\n\n' +
      'Time from "edit a component file" to "next GET / reflects the change" via `bun --watch` server restart. place-ts has no module-level HMR; this is the practical edit→render dev cycle.\n\n' +
      "Generated by `bun scripts/bench-dev-cycle.ts`. Don't manually edit — re-run the script to refresh.\n\n" +
      '| Date | Components | Trials | Cold start (ms) | p50 (ms) | p95 (ms) | p99 (ms) | Mean (ms) |\n' +
      '|---|---|---|---|---|---|---|---|\n'
    await writeFile(outFile, header)
  } else {
    // Already has header; just append the row.
    const _existing = readFileSync(outFile, 'utf8') // touch to ensure file readable
    void _existing
  }
  const { appendFile } = await import('node:fs/promises')
  await appendFile(outFile, row)
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv)
  const result = await run(args)

  const outFile = join(process.cwd(), 'docs/benchmarks/dev-cycle.md')
  await mkdir(join(process.cwd(), 'docs/benchmarks'), { recursive: true })
  await appendMarkdown(result, outFile)
}

main().catch((_err) => {
  process.exit(1)
})
