// Forbidden-import probe — the Tier 20 entrypoint-split enforcement.
//
// Client safety in place is meant to be an *impossible import graph*,
// not "the `__PLACE_BROWSER__` define happens to delete the bad
// branch." This probe is the runtime proof: it builds the docs
// production bundle and scans every emitted client/island `.js` for
// server- or build-only tokens that must NEVER reach the browser.
//
// Reliable tokens only. A minifier renames local identifiers, so
// `renderToString`-by-name is not a dependable signal — but import
// specifiers (`node:fs`) and global property access (`Bun.serve`)
// survive minification verbatim. Size is the backstop: if the SSR
// pipeline (`_serveImpl`, ~1,900 LOC) leaked, the island bundles
// would balloon by hundreds of KB.
//
// Exit code: 0 = clean, 1 = leak found, 2 = build/setup failure.
// Wired into `bun run ci`.
//
// Writes `docs/probes/forbidden-imports.md`.

import { readdir, readFile, writeFile } from 'fs/promises'
import { join, resolve } from 'path'
import { gzipSync } from 'zlib'

const FORBIDDEN: ReadonlyArray<{ token: string; why: string }> = [
  { token: 'node:', why: 'a node: builtin import — server/build only' },
  { token: 'Bun.serve', why: 'the HTTP server — server only' },
  { token: 'Bun.build', why: 'the bundler — build only' },
  { token: 'Bun.file', why: 'filesystem read — server/build only' },
  { token: 'Bun.spawn', why: 'subprocess spawn — server/build only' },
  { token: 'child_process', why: 'subprocess — server/build only' },
  { token: 'fs/promises', why: 'filesystem — server/build only' },
]

const docsDir = resolve(import.meta.dir, '..')
const distDir = join(docsDir, 'dist')

async function buildDocs(): Promise<void> {
  console.log('forbidden-imports: building docs (production)…')
  const proc = Bun.spawn(['bun', 'run', 'build'], {
    cwd: docsDir,
    stdout: 'pipe',
    stderr: 'pipe',
  })
  const code = await proc.exited
  if (code !== 0) {
    console.error('forbidden-imports: docs build FAILED:')
    console.error((await new Response(proc.stderr).text()).slice(-2000))
    process.exit(2)
  }
}

async function walkJs(dir: string): Promise<string[]> {
  const out: string[] = []
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    if (e.isDirectory()) out.push(...(await walkJs(p)))
    else if (e.name.endsWith('.js')) out.push(p)
  }
  return out
}

async function main(): Promise<number> {
  await buildDocs()

  const files = (await walkJs(distDir)).sort()
  if (files.length === 0) {
    console.error('forbidden-imports: no client/island .js emitted — nothing to scan.')
    return 2
  }

  const hits: Array<{ file: string; token: string; why: string }> = []
  const rows: Array<{ file: string; raw: number; gz: number }> = []

  for (const path of files) {
    const buf = await readFile(path)
    const rel = path.slice(distDir.length + 1)
    rows.push({ file: rel, raw: buf.length, gz: gzipSync(buf).length })
    const text = buf.toString('utf8')
    for (const { token, why } of FORBIDDEN) {
      if (text.includes(token)) hits.push({ file: rel, token, why })
    }
  }

  const totalRaw = rows.reduce((s, r) => s + r.raw, 0)
  const totalGz = rows.reduce((s, r) => s + r.gz, 0)

  const lines: string[] = [
    '# Forbidden-import scan — client / island bundles',
    '',
    '> Generated by `bun examples/docs/probes/forbidden-imports.ts`.',
    '> Builds the docs production output and scans every emitted client',
    '> `.js` for server/build-only tokens that must never reach a browser.',
    '> This is the Tier 20 entrypoint-split enforcement: client safety is',
    "> an impossible import graph, not define-based dead-code elimination.",
    '',
    hits.length === 0
      ? `## CLEAN — ${files.length} client bundles, zero forbidden tokens`
      : `## LEAK — ${hits.length} forbidden token(s) found`,
    '',
  ]
  if (hits.length > 0) {
    lines.push('| File | Token | Why it must not ship |', '|---|---|---|')
    for (const h of hits) lines.push(`| \`${h.file}\` | \`${h.token}\` | ${h.why} |`)
    lines.push('')
  }
  lines.push('| Bundle | Raw | Gzipped |', '|---|--:|--:|')
  for (const r of rows) lines.push(`| \`${r.file}\` | ${r.raw} B | ${r.gz} B |`)
  lines.push(`| **total (${files.length})** | **${totalRaw} B** | **${totalGz} B** |`, '')

  await writeFile(
    resolve(docsDir, '..', '..', 'docs', 'probes', 'forbidden-imports.md'),
    lines.join('\n') + '\n',
  )

  for (const r of rows) {
    console.log(
      `  ${r.file.padEnd(44)} ${String(r.raw).padStart(7)} B raw  ${String(r.gz).padStart(6)} B gz`,
    )
  }
  console.log('')
  if (hits.length === 0) {
    console.log(
      `CLEAN — ${files.length} client bundles, no node:/Bun.serve/Bun.build/` +
        `child_process leak. Total ${totalRaw} B raw / ${totalGz} B gz.`,
    )
    console.log('Report → docs/probes/forbidden-imports.md')
    return 0
  }
  console.error(`LEAK — ${hits.length} forbidden token(s):`)
  for (const h of hits) console.error(`  ${h.file}: ${h.token} — ${h.why}`)
  return 1
}

main().then(
  (code) => process.exit(code),
  (err) => {
    console.error('forbidden-imports: unexpected error:', err)
    process.exit(2)
  },
)
