// T5-A follow-on — per-route bundle simulation.
//
// Today the docs app ships ONE shared client bundle: every page's view
// code, every component, every layout, all bundled together. This
// probe simulates the win we'd get from per-route bundle splitting:
//   - For each top-level page, build an entry that imports the
//     page's view + the layout + the framework runtime.
//   - Measure the result.
//   - Compare to the shared-bundle size (1 build for all 20+ pages
//     today).
//
// The "win" = (current shared bundle) − (avg per-route bundle).
// If the win is large, per-route splitting is a slam-dunk prerequisite
// to T5-B/C.

import { mkdir, readdir, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { gzipSync } from 'node:zlib'

const ROOT = resolve(import.meta.dir, '../../..')
const PAGES_DIR = resolve(import.meta.dir, '../src/pages')
const TMP = resolve(import.meta.dir, '.tmp/per-route')
await mkdir(TMP, { recursive: true })

const fmt = (n: number): string =>
  n >= 1024 ? `${(n / 1024).toFixed(2)} KB` : `${n} B`

const EXTERNAL = [
  '@tailwindcss/node',
  '@tailwindcss/oxide',
  'tailwindcss',
  'lightningcss',
  'bun:sqlite',
  'bun:test',
  'bun:ffi',
  'bun:redis',
]

// Find every .page.tsx file under pages/. Recursive.
async function findPages(dir: string, acc: string[] = []): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true })
  for (const e of entries) {
    const full = join(dir, e.name)
    if (e.isDirectory()) await findPages(full, acc)
    else if (e.isFile() && e.name.endsWith('.page.tsx')) acc.push(full)
  }
  return acc
}

const pages = await findPages(PAGES_DIR)
console.log(`Found ${pages.length} pages to simulate`)

interface RouteResult {
  page: string
  raw: number
  gzipped: number
}

async function simulatePage(pagePath: string): Promise<RouteResult> {
  const name = pagePath.replace(`${PAGES_DIR}/`, '').replace(/\.page\.tsx$/, '')
  const entryPath = join(TMP, `${name.replace(/\//g, '__')}.ts`)
  await mkdir(resolve(entryPath, '..'), { recursive: true })
  // Build a per-page client entry: mount THIS page only.
  // Mimic what an islands-friendly per-route bundle would import:
  // the page module + the layout + minimal framework runtime to mount.
  await writeFile(
    entryPath,
    `// Per-route simulation entry for ${name}.
// Imports: the page itself, the docs layout, and the framework entry
// for client-side mount. This is what a per-route split would ship.

import { mount } from '@place/component'
import page from '${pagePath}'
import { docsLayout } from '${resolve(import.meta.dir, '../src/layouts/docs.layout.tsx')}'

;(globalThis as Record<string, unknown>).__page = page
;(globalThis as Record<string, unknown>).__layout = docsLayout
;(globalThis as Record<string, unknown>).__mount = mount
`,
  )
  const out = await Bun.build({
    entrypoints: [entryPath],
    target: 'browser',
    format: 'esm',
    minify: true,
    sourcemap: 'none',
    define: { __PLACE_BROWSER__: 'true' },
    external: EXTERNAL,
  })
  if (!out.success) {
    for (const log of out.logs) console.error(log)
    return { page: name, raw: -1, gzipped: -1 }
  }
  const buf = await out.outputs[0]!.arrayBuffer()
  return { page: name, raw: buf.byteLength, gzipped: gzipSync(new Uint8Array(buf)).byteLength }
}

console.log('Simulating per-route bundles...')
const results: RouteResult[] = []
for (const p of pages) {
  const r = await simulatePage(p)
  results.push(r)
  console.log(`  ${r.page.padEnd(50)} ${fmt(r.raw).padStart(12)} raw / ${fmt(r.gzipped).padStart(10)} gzip`)
}

results.sort((a, b) => b.gzipped - a.gzipped)

const totalGzip = results.reduce((a, b) => a + b.gzipped, 0)
const avgGzip = totalGzip / results.length
const minGzip = Math.min(...results.map((r) => r.gzipped))
const maxGzip = Math.max(...results.map((r) => r.gzipped))

console.log('\n=== Per-route simulation ===')
console.log(`Pages: ${results.length}`)
console.log(`Avg gzip: ${fmt(avgGzip)}`)
console.log(`Min gzip: ${fmt(minGzip)}`)
console.log(`Max gzip: ${fmt(maxGzip)}`)
console.log(`Shared bundle today (all pages): 65.40 KB gzip`)
console.log(`Per-route win: ${fmt(65 * 1024 - avgGzip)} gzip avg per page`)

const mdLines: string[] = []
mdLines.push('# T5-A — per-route bundle simulation')
mdLines.push('')
mdLines.push(`> Generated by \`examples/docs/probes/per-route-simulation.ts\` on ${new Date().toISOString().slice(0, 10)}.`)
mdLines.push('')
mdLines.push('## What this measures')
mdLines.push('')
mdLines.push('Today the docs app ships ONE shared client bundle (65.40 KB gzipped on every page). This probe simulates per-route splitting: each page becomes its own client entry, bundled separately. Tree-shaking strips everything the page doesn\'t use.')
mdLines.push('')
mdLines.push('## Results per page')
mdLines.push('')
mdLines.push('| Page | Raw | Gzipped |')
mdLines.push('|---|---:|---:|')
for (const r of results) {
  mdLines.push(`| \`${r.page}\` | ${fmt(r.raw)} | ${fmt(r.gzipped)} |`)
}
mdLines.push('')
mdLines.push('## Summary')
mdLines.push('')
mdLines.push(`- **Pages:** ${results.length}`)
mdLines.push(`- **Avg per-route gzipped:** ${fmt(avgGzip)}`)
mdLines.push(`- **Min per-route gzipped:** ${fmt(minGzip)}`)
mdLines.push(`- **Max per-route gzipped:** ${fmt(maxGzip)}`)
mdLines.push(`- **Current shared bundle:** 65.40 KB gzipped`)
mdLines.push(`- **Per-route win (avg):** ${fmt(65 * 1024 - avgGzip)} gzip per page`)
mdLines.push(`- **Reduction:** ~${(((65 * 1024 - avgGzip) / (65 * 1024)) * 100).toFixed(0)}% of bundle size on a typical page`)
mdLines.push('')
mdLines.push('## Interpretation')
mdLines.push('')
mdLines.push('If the per-route simulation shows pages averaging much less than 65 KB, then **per-route bundle splitting is a prerequisite to T5-B/C** — it alone delivers a multi-fold reduction with no other change to the framework.')
mdLines.push('')
mdLines.push('Note: this simulation overestimates the win slightly because the layout chrome (sidebar, search palette, ToC) IS shared across pages. A production per-route splitter would emit:')
mdLines.push('- 1 shared chunk for layout + framework runtime')
mdLines.push('- N small per-page chunks (just the page\'s own view code)')
mdLines.push('')
mdLines.push('The shared chunk would be loaded once and cached; each navigation only fetches the small per-page chunk. So actual gains are larger than this simulation\'s average suggests (the layout is amortized).')

const outPath = resolve(ROOT, 'docs/probes/per-route-simulation.md')
await writeFile(outPath, mdLines.join('\n'))
console.log(`\nWritten: ${outPath}`)
